version: '3.8'

services:
  postgres-db:
    container_name: 'postgres-db'
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password

  covid-api:
    container_name: covid-api
    image: test-covid-api
    ports:
      - 8080:8080
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres-db:
        condition: service_started