spring:
  liquibase:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/covid-db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate.ddl-auto: update
    properties.hibernate.format_sql: true

logging:
  level:
    org:
      springframework:
        security: TRACE
    io:
      micrometer: DEBUG

management:
  endpoints:
    jmx:
      exposure:
        include: info,health,beans,metrics,endpoints,mappings
    web:
      exposure:
        include: health,info,prometheus,metrics